name: PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  pr-title:
    name: pr-title
    uses: abijith-suresh/workflows/.github/workflows/conventional-commit-title.yml@e2088a6610d40b7c978e6e8e7ca3272be8d06020 # v0.4.0
    permissions:
      pull-requests: read
